### ISSUE TITLE
Levenshtein Distance Performance 

### ISSUE THREAD

**Issue by symb10z** [abstractqqq/polars_ds_extension#17]
Is it possible to add Damerau-Levenshtein distance to str_ext?
May be use crates strsim, triple_accel, distance, textdistance etc.?

**Comment by abstractqqq** [comment]
I think the plan would be to pick either strsim or triple_accel as the fuzzy search backend of this package.. Thanks for letting me know about the packages

**Comment by abstractqqq** [comment]
I tried strsim and triple_accel. 

triple_accel also has wrong output for you example, and does not perform well for some reason.

strsim, on the other hand, gives me a free 3x speed up without parallelization and it has a more complete feature set.

I am integrating with strsim and trying to bring most of the functionalities from strsim to Polars.

**Comment by symb10z** [comment]
I've done some simple benchmarking using attached snipped and got resulsts bellow.
As you can see ds_extention and rapidfuzz runs same time, but DS runs in parallel on all 16 cores and RapidFuzz runs single core due to GIL, so there is at least 16x speed improvement possibility.
```shell
Word pairs:1000000
DS parallel time:101.6 sec, Len: 1000
RapidFuzz time:103.69 sec, Len: 1000
``` 
The code:
```python
import polars as pl, numpy as np, string, time
from polars_ds import StrExt
from rapidfuzz.distance.Levenshtein import distance

Letters = np.array(list(string.ascii_letters))

words_df=pl.DataFrame({'dummy':[1]*1000})
words_df=words_df.with_columns(pl.lit(np.random.choice(Letters, size=(words_df.height,100))).list.join('').alias('word')).drop('dummy')
word_pairs_df=words_df.join(words_df,how='cross')
print(f"Word pairs:{len(word_pairs_df)}")

t0=time.perf_counter()
word_pairs_ds=word_pairs_df.with_columns(
    pl.col("word").str_ext.levenshtein_dist(pl.col("word_right"),parallel=True).alias("distance")
).filter(pl.col('distance').le(2))
print(f"DS parallel time:{round(time.perf_counter()-t0,2)} sec, Len: {len(word_pairs_ds)}")
word_pairs_rf=word_pairs_df.with_columns(
                    pl.struct(["word","word_right"])
                    .map_elements(lambda x: distance(str(x["word"]),str(x["word_right"])))
                    .alias("distance")
                    ).filter(pl.col('distance').le(2))
print(f"RapidFuzz time:{round(time.perf_counter()-t0,2)} sec, Len: {len(word_pairs_rf)}")
```

**Comment by abstractqqq** [comment]
> I've done some simple benchmarking using attached snipped and got resulsts bellow. As you can see ds_extention and rapidfuzz runs same time, but DS runs in parallel on all 16 cores and RapidFuzz runs single core due to GIL, so there is at least 16x speed improvement possibility. _remark: i've changed RapidFuzz function from DamerauLevenshtein to Levenshtein_
> 
> ```shell
> Word pairs:1000000
> DS parallel time:101.6 sec, Len: 1000
> RapidFuzz time:103.69 sec, Len: 1000
> ```
> 
> The code:
> 
> ```python
> import polars as pl, numpy as np, string, time
> from polars_ds import StrExt
> from rapidfuzz.distance.Levenshtein import distance
> 
> Letters = np.array(list(string.ascii_letters))
> 
> words_df=pl.DataFrame({'dummy':[1]*1000})
> words_df=words_df.with_columns(pl.lit(np.random.choice(Letters, size=(words_df.height,100))).list.join('').alias('word')).drop('dummy')
> word_pairs_df=words_df.join(words_df,how='cross')
> print(f"Word pairs:{len(word_pairs_df)}")
> 
> t0=time.perf_counter()
> word_pairs_ds=word_pairs_df.with_columns(
>     pl.col("word").str_ext.levenshtein_dist(pl.col("word_right"),parallel=True).alias("distance")
> ).filter(pl.col('distance').le(2))
> print(f"DS parallel time:{round(time.perf_counter()-t0,2)} sec, Len: {len(word_pairs_ds)}")
> word_pairs_rf=word_pairs_df.with_columns(
>                     pl.struct(["word","word_right"])
>                     .map_elements(lambda x: distance(str(x["word"]),str(x["word_right"])))
>                     .alias("distance")
>                     ).filter(pl.col('distance').le(2))
> print(f"RapidFuzz time:{round(time.perf_counter()-t0,2)} sec, Len: {len(word_pairs_rf)}")
> ```

Thank you so much! In the next release, it will be renamed to simply levenshtein. 

The updated version will be at least 2x faster if we run in parallel, and I am looking into ways to run faster.

![image](https://github.com/abstractqqq/polars_ds_extension/assets/72534736/c0ac2a91-811d-4e09-816a-520c67779301)

**Comment by abstractqqq** [comment]
https://github.com/abstractqqq/polars_ds_extension/pull/18

**Comment by symb10z** [comment]
Hi, all works amazing, thanks for your efforts.
I've done some research and found out possibly faster implementation
Could you please check it out: [https://github.com/thaumant/eddie/blob/master/benchmarks.md](url)
And it supports utf!

**Comment by abstractqqq** [comment]
> Hi, all works amazing, thanks for your efforts. I've done some research and found out possibly faster implementation Could you please check it out: [https://github.com/thaumant/eddie/blob/master/benchmarks.md](url) And it supports utf!

I tried Eddie. Non-parallel Levenshtein (Not all UTF8, only ascii) is 8.2s on the test you provided, while Strsim is 10s (supports all UTF8 characters). Eddie's code make it hard to parallelize so I didn't try the parallel version. Eddie is also not  actively maintained.. So I don't think I will switch to Eddie.

**Comment by abstractqqq** [comment]
FYI, more research led me to this article, and Meyer's bitwise parallel algorithm.

https://ceptord.net/20200815-Comparison.html

**Comment by abstractqqq** [comment]
Runtime seems to be very different when you are not on completely randomly generated string, and when string sizes are small.

![image](https://github.com/abstractqqq/polars_ds_extension/assets/72534736/88f69f00-88e7-4f44-aced-9d1bf4ca5e7e)


I was not able to understand Meyer's bit parallel algorithm for edit distance. But right now I implemented the trick in 3.2 of this post: https://ceptord.net/wagner-fischer/index.html

Also I learned about bounded levenshtein distance. So if you do not need the actual distance value, and you are only interested in elements that are within k distance, I think it would be better if I can provide an expression like

```Python
# Returns true or false and checks if levenshtein distance is within 3
pl.col("a").str_ext.levenshtein_within(pl.col("b"), k = 3) 
```

This would be even faster since bounded Levenshtein can cut off a lot of computations. I will try to implement it soon.

**Comment by maxbachmann** [comment]
for short strings I expect that most of the performance difference is actually just Python function call overhead since it's calling the function repeatedly. You rust implementation on the other hand can directly access the underlying elements without going through Python. 

When running the following test:
```python
from timeit import timeit

print(timeit("""
df.select(
    pl.struct(["a", "b"])
    .map_elements(lambda x: no_op(x["a"], x["b"]))
)
""",
setup="""
import polars as pl

def no_op(s1, s2):
    return s1 == s2

df=pl.DataFrame({"a": ["aaaaaaaaaa"]*20, "b": ["bbbbbbbbbbb"]*20})
df =pl.concat([df]*50_000)
""", number=1
))

print(timeit("""
df.select(
    pl.struct(["a", "b"])
    .map_elements(lambda x: distance(x["a"], x["b"]))
)
""",
setup="""
from rapidfuzz.distance.Levenshtein import distance
import polars as pl

df=pl.DataFrame({"a": ["aaaaaaaaaa"]*20, "b": ["bbbbbbbbbbb"]*20})
df =pl.concat([df]*50_000)
""", number=1
))
```

I get 650ms for the first benchmark and 800ms for the second one. So most of the time spend is indeed just overhead of calling Python functions :stuck_out_tongue_closed_eyes: 

Rapidfuzz has a couple of API that perform similar lowering, but none to compare to lists of strings element by element. This has been requested e.g. in https://github.com/maxbachmann/RapidFuzz/issues/344, but I am still very much unsure about the appropriate API for these kinds of comparisons.

Btw cool to see you implementing Ukkonens optimization. Especially for very long sequences this does wonders (I had people compare texts with >100k characters). 

My implementation of Levenshtein has a couple of different implementations:
- for strings <= 64 characters -> myers/hyrros algorithm with a single bit vector
- for strings > 64 characters but with a width of the ukkonen band < 64 characters
   - if bitvectors are already calculated an optimized version always using two bitvectors
   - if they are not calculated calculate the bitvectors on the fly
- for strings > 64 characters -> myers/hyrros algorithm combined with ukkonens optimization. The band is dynamically downsized during the calculation if possible
- for very low cutoff values (<=3) brute force the levenshtein distance, since there are not many possible variations
- for short texts there is a simd implementation which allows comparing multiple texts with a single one. This is used when comparing all elements of a list with all elements of a different list. With Avx2 this can e.g. compare 4 64 char strings or 32 8 char strings.

In addition the user can provide a hint of the expected distance. In this case I calculate the distance using this hint as cutoff value for the ukkonens optimization. Each time I find the distance to be higher than the cutoff I double the hint and repeat the process. This can be a lot faster if the hint makes sense, but can be slower when it's incorrect.

**Comment by abstractqqq** [comment]
> I get 650ms for the first benchmark and 800ms for the second one. So most of the time spend is indeed just overhead of calling Python functions 😝

Makes total sense! Thank you so much and this knowledge is very valuable. I am integrating your library right now

**Comment by abstractqqq** [comment]
> 👍 Let me know if you run into any parts of the API that seem strange / you think could be improved.

It is a smooth sail even for a Rust beginner like me. The only part that is slightly annoying is that I need to fill in a lot of None. I guess that is inevitable and is really a small inconvenience.

**Comment by abstractqqq** [comment]
@maxbachmann Just want to say thank you again. Truly amazing work. The basics are merged. https://github.com/abstractqqq/polars_ds_extension/pull/23
