### ISSUE TITLE
ROC-AUC not working properly

### ISSUE THREAD

**Issue by dkulemin** [abstractqqq/polars_ds_extension#282]
Hi!
It's seems like function query_roc_auc not working properly in case when you have targets = [0, 1] and predictions = [0.5, 0.5].
Function returns -0.0 value, when it should return 0.5 value, as sklearn's roc_auc_score does it.

code to reproduce:
```
roc_auc_score([0, 1], [0.5, 0.5])

pl.DataFrame({"a": [0, 1], "b": [0.5, 0.5]}).select(pds.query_roc_auc(pl.col('a'), pl.col('b')))
```

**Comment by abstractqqq** [comment]
Yea you are right..

The reason for this is that I didn't deal with the case when the predicted probability is a single value, which results in a single value for TPF and FPR, which messed up the area under curve calculation. (because to run a AUC approximation we need 2 points at least. I do need to append (0, 0) so that we always have 2 points in that case. )

Here is the fix: https://github.com/abstractqqq/polars_ds_extension/pull/283

This one seems already quite rare. It's good to cover more edge cases, but I cannot promise the current impl covers all.
