### ISSUE TITLE
Roc_curve

### ISSUE THREAD

**Issue by hiqishen** [abstractqqq/polars_ds_extension#298]
Will Roc_curve could be added in the future?

**Comment by abstractqqq** [comment]
Absolutely. The only reason it is not implemented is that I haven't decided on a plotting backend yet. 

I am debating between plotly and altair. Previously, altair added polars support (via narwhals) and so I switched to altiar. But I heard that plotly is also going to add polars support soon. I prefer plotly personally. I am waiting now for the news to be official and I will try out the new plotly. 

Then I will add more plots.

**Comment by abstractqqq** [comment]
Thanks Macro. Been too busy with work and life in this holiday season... And then I taksed myself  with Advent of Code 2024 and literally am squeezing time out for oss.. Hopefully it gets better after holidays

**Comment by abstractqqq** [comment]
I have decided to continue using Altair for all plots (because Altair fits very well with Marimo, Altair has a Rust backend, etc. etc.)

I am in the process of refactoring the whole Diagnosis and plotting module. And I have roc_curve built as shown in the picture below. This is going to be a big refactor and won't be merged any time soon. But I should have something by the end of Jan.

![image](https://github.com/user-attachments/assets/b30ffaa5-1dee-4b86-adba-84cf90a23fa7)
