### ISSUE TITLE
KNN for string distance metrics

### ISSUE THREAD

**Issue by coinflip112** [abstractqqq/polars_ds_extension#50]
It would be extremely useful to use `knn_ptwise` on a string column (with string distance metrics). This should be feasible in principle, right? Levenshtein distance for example defines a metric space. Does [KDTree](https://docs.rs/kdtree/latest/kdtree/distance/index.html) allow for different distances?

**Comment by abstractqqq** [comment]
Yes theoretically it is possible but the kdtree package currently does not allow strings. I can maybe use [u8] to represent strings, but the Levenshtein distances in this package is based on RapidFuzz's implementation, which is based on chars instead of [u8] so that is it correct even in other languages like Russian. In short, to do that is possible but requires way too much hacking right now...

**Comment by coinflip112** [comment]
Makes sense. Haven't worked in rust before but it's on my "would like to but don't have time for list". If it ever does I could take a crack at it 😅

**Comment by abstractqqq** [comment]
I would close this issue since I won't be implementing it for now. But it is something on my mind and feel free to pin me if you find something that can facilitate the implementation. Thanks!

**Comment by abstractqqq** [comment]
An inefficient implementation has been added. Please refer to the examples. I believe it is available >= 0.2.3

**Comment by coinflip112** [comment]
Nice! Thanks! Tested and works exactly as I'd expect :) 🙏
