### ISSUE TITLE
Adding L2 penalty to LSTQ --> ridge regression

### ISSUE THREAD

**Issue by furlat** [abstractqqq/polars_ds_extension#63]
I saw the docstring about numerical instability of the linear squares models, it should be pretty simple to add a l2 regularization parameter to the closed form solution (even simpler via SVD where for one svd you get the weight matrix for all regularization parameters in linear time but that is another primitive missing I guess) . 

Going l1l2 elastic net etc requires iterative solving and complicates things but doing l2 regulariztion, solving via SVD or using the kernel ridge instead of working in the feature maps is a each few line of algebras and allows closed form solutions.

**Comment by abstractqqq** [comment]
If you are not aware, this package has this implemented: https://github.com/azmyrajab/polars_ols

**Comment by abstractqqq** [comment]
> Fantastic package, thanks a lot! Sorry I disappeared I see you made a lot of great improvements, I am eager to explore polar ds again :)

We are trying to add more text sanitizing methods. Meanwhile, I de-prioritized graph related content because Graphs can have inherently many representations: One id column + another id column representing connections or one id column + another column of list of ids representing connections.. ID column can be string, or int... It is better to have a persistent data structure for these things rather than using them in a single query.. It is also hard to construct them too.

Probably in the future a dedicated graph module will be done, more likely a direct wrapper to the underlying Rust package.

**Comment by furlat** [comment]
Yes I followed all your steps and tested locally, and noticed the same problems!

I am starting to work on a (still soloware level) package for seamless serverless gpu/cpu computing on polars frames for this sort of computations that are too heavy and thread locking to run locally. https://github.com/Neural-Dragon-AI/Cynde/tree/main [mostly batched LLM usage and training trees ensembles].

I will probably integrate polars ds soon to postprocess the results and compute metrics. And potentially that ols package looks great for training linear models locally before jumping into cloud trained gradient boosting trees.

**Comment by furlat** [comment]
sorry for misdirecting you into the graph direction that does not fit as elegantly in the framework !

**Comment by abstractqqq** [comment]
> sorry for misdirecting you into the graph direction that does not fit as elegantly in the framework !

No worries. I learned a lot of things too

**Comment by abstractqqq** [comment]
FYI, I have implemented ridge, rolling, recursive lstsq in polars_ds.
